version: '2.1'
services:
  clashs:
    image: dreamacro/clash
    container_name: clashs
    networks:
      - clash-all
    ports:
      - 9090:9090 #外部控制端
      #以下三个的常用的代理端口映射，到时间自己访问ui界面修改就可以，
      - 7890:7890
      - 7891:7891
      - 7892:7892
      - 7777:7777
    volumes:
      - ./data/config.yaml:/root/.config/clash/config.yaml
    restart: always 
  
  clashui:
    container_name: clashui
    # image: ghcr.io/haishanh/yacd
    image: haishanh/yacd
    networks:
      - clash-all
    ports:
      - 7900:80
    restart: always 

  # 订阅链接转换合并后端,端口为25500
  subconverter:
    image: tindy2013/subconverter
    container_name: subconverter

    ###使用fastgithub的配置，需要设置此dns，且必须在host模式下
    network_mode: host
    dns:
      - 127.0.0.1   
    #############自己注释或者取消注释
    

    ##自己设置代理则建议使用此设置，记得修改./data/pref.toml文件
    # networks:
      # clash-all:
    # ports:
      # - "25500:25500"
    # volumes:
      # - ./data/pref.toml:/base/pref.toml
    ##########自己注释或者取消注释

    restart: always

  ## 生成指向后端的订阅转换链接，访问链接后，在update脚本中默认关闭此服务
  subweb:
    image: stilleshan/subweb
    container_name: subweb
    networks:
      - clash-all
    ports:
      - 7902:80
    restart: always
      
networks:
  clash-all:

